version: 2.1

commands:
  setup:
    description:"Checkout code and resolve dependencies"
    steps:
      - checkout
      - run: mvn dependency:go-offline

jobs:
  build:
    docker:
      - image: circleci/openjdk:14-jdk-buster-node
    steps:
      - setup
      - run: mvn package
  test:
    docker:
      - image: circleci/openjdk:14-jdk-buster-node
    steps:
      - setup
      - run: mvn verify sonar:sonar
      - mvn test
      - store_test_results:
          path: target/surefire-reports

workflows:
  main:
    jobs:
      - build
      - test:
          context: SonarCloud