version: 2.1

commands:
  setup:
    description: "Checkout code and resolve dependencies"
    steps:
      - checkout
      - run: mvn dependency:go-offline

jobs:
  build:
    docker:
      - image: circleci/openjdk:14-jdk-buster-node
    steps:
      - setup
      - run: mvn package
  test:
    docker:
      - image: circleci/openjdk:14-jdk-buster-node
    steps:
      - setup
      - run: mvn verify sonar:sonar
      - run: mvn test
      - store_test_results:
          path: target/surefire-reports
  check_coverage:
    docker:
      - image: circleci/openjdk:14-jdk-buster-node
    steps:
      - setup
      - run: mvn cobertura:cobertura
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  main:
    jobs:
      - build
      - test:
          context: SonarCloud
      - check_coverage